### ISSUE TITLE
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.

### ISSUE THREAD

**Issue by noOne228** [huntfx/MouseTracks#64]
when i run start_tracking.bat i get this:
````
C:\Users\User\Downloads\MouseTracks-master\MouseTracks-master>echo..\env\scripts\python start_tracking.py 1>start_tracking.bat

C:\Users\User\Downloads\MouseTracks-master\MouseTracks-master>echo..\env\scripts\python generate_images.py 1>generate_images.bat

C:\Users\User\Downloads\MouseTracks-master\MouseTracks-master>start_tracking.bat

C:\Users\User\Downloads\MouseTracks-master\MouseTracks-master>.\env\scripts\python start_tracking.py
Traceback (most recent call last):
  File "C:\Users\User\Downloads\MouseTracks-master\MouseTracks-master\start_tracking.py", line 11, in <module>
    from mousetracks.track import track
  File "C:\Users\User\Downloads\MouseTracks-master\MouseTracks-master\mousetracks\track\__init__.py", line 7, in <module>
    from .main import track, RefreshRateLimiter
  File "C:\Users\User\Downloads\MouseTracks-master\MouseTracks-master\mousetracks\track\main.py", line 14, in <module>
    from .background import background_process, running_processes, monitor_offset, _notify_queue_size
  File "C:\Users\User\Downloads\MouseTracks-master\MouseTracks-master\mousetracks\track\background.py", line 13, in <module>
    from ..utils import numpy
  File "C:\Users\User\Downloads\MouseTracks-master\MouseTracks-master\mousetracks\utils\numpy.py", line 18, in <module>
    'float_': numpy.float_,
  File "C:\Users\User\Downloads\MouseTracks-master\MouseTracks-master\env\lib\site-packages\numpy\__init__.py", line 426, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
```

**Comment by huntfx** [comment]
Hey, I'll push out a fix, sorry I didn't spot this earlier. I've finally started work on a rewrite anyway which will be using the latest of everything.
